# Generated by Django 3.0.4 on 2020-04-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200408_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.UUIDField(editable=False, unique=True, verbose_name=' username'),
        ),
    ]
