# Generated by Django 3.0.4 on 2020-04-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200408_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name=' username'),
        ),
    ]
