# Generated by Django 3.0.4 on 2020-04-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200408_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='university_abb',
            field=models.CharField(max_length=20, unique=True, verbose_name=' username'),
        ),
    ]
