# Generated by Django 3.0.4 on 2020-04-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200408_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='university_abb',
            field=models.CharField(max_length=20, verbose_name=' University Abbreviation'),
        ),
    ]
