# Generated by Django 3.0.4 on 2020-04-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200408_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='university_abb',
        ),
        migrations.RemoveField(
            model_name='account',
            name='university_name',
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default=2, max_length=255, unique=True, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
