# Generated by Django 3.0.4 on 2020-04-08 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_full_name', models.CharField(max_length=255, verbose_name='University full name')),
                ('university_name_abb', models.CharField(max_length=15, verbose_name='University full name')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Added date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='University Admin')),
            ],
        ),
    ]
