# Generated by Django 3.0.4 on 2020-04-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(editable=False, unique=True, verbose_name='unique id')),
                ('title', models.CharField(max_length=255, verbose_name='Short title')),
                ('description', models.CharField(max_length=1000, verbose_name='Product description')),
                ('price', models.FloatField(verbose_name='Price per unique use')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Added date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
        ),
    ]
