# Generated by Django 3.0.5 on 2020-04-10 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='unique id')),
                ('title', models.CharField(max_length=255, verbose_name='Short title')),
                ('description', models.CharField(max_length=1000, verbose_name='Product description')),
                ('price', models.FloatField(verbose_name='Price per unique use')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Added date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('slug', models.SlugField(editable=False, max_length=500, null=True, unique=True, verbose_name=' Slug Url')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
            ],
        ),
    ]
