# Generated by Django 3.0.4 on 2020-04-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200408_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=500, null=True, unique=True, verbose_name=' Slug Url'),
        ),
    ]
