# Generated by Django 3.0.5 on 2020-04-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(editable=False, max_length=500, null=True, unique=True, verbose_name=' Slug Url'),
        ),
    ]
