# Generated by Django 3.0.5 on 2020-04-09 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20200409_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='user_added',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
    ]
