# Generated by Django 3.0.5 on 2020-04-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_user_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='user_added',
            new_name='user',
        ),
    ]
